### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by sardaukar** [potahtml/mpa-archive#2]
I ran `mpa https://blog.nootch.net` and got

```
file:///home/sardaukar/.asdf/installs/nodejs/20.5.0/lib/node_modules/mpa-archive/src/archive.js:239
			body = body.toString().replaceAll(origin, '')
			            ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at onFile (file:///home/sardaukar/.asdf/installs/nodejs/20.5.0/lib/node_modules/mpa-archive/src/archive.js:239:16)
    at fetchURL (file:///home/sardaukar/.asdf/installs/nodejs/20.5.0/lib/node_modules/mpa-archive/src/archive.js:319:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

What am I doing wrong?

**Comment by titoBouzout** [comment]
Is that always reproducible? I cannot reproduce with node v21.6.2

**Comment by sardaukar** [comment]
I see the error consistently on 20.5.0 (Linux) and 21.6.2 too:

```
🔗 https://blog.nootch.net/tags/security/index.xml
✔  https://blog.nootch.net/tags/security/index.xml
🔗 https://googleads.g.doubleclick.net/pagead/id
🛑  https://googleads.g.doubleclick.net/pagead/id
file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:239
			body = body.toString().replaceAll(origin, '')
			            ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at onFile (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:239:16)
    at fetchURL (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:319:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.6.2
```

**Comment by sardaukar** [comment]
More on the second run:

```
✔  https://blog.nootch.net/page/4/
🧭 https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus_BBS_RELEASE_1.7.lha
🧭 about:blank
🧭 https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus.key
🧭 about:blank
🛑  https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus_BBS_RELEASE_1.7.lha
Error: net::ERR_ABORTED at https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus_BBS_RELEASE_1.7.lha
    at navigate (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:175:27)
    at async Deferred.race (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:141:25)
    at async CdpPage.goto (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:561:20)
🍳 https://blog.nootch.net/post/page/4/
🛑  https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus.key
Error: net::ERR_ABORTED at https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus.key
    at navigate (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:175:27)
    at async Deferred.race (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:33:20)
    at async CdpFrame.goto (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:141:25)
    at async CdpPage.goto (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:561:20)
🔗 https://blog.nootch.net/tags/docker/index.xml
✔  https://blog.nootch.net/post/page/4/
✔  https://blog.nootch.net/tags/docker/index.xml
🍳 https://blog.nootch.net/page/5/
✔  https://blog.nootch.net/page/5/
🧭 https://blog.nootch.net/post/recently-ive-been-mostly-reading/teropa.info/blog/2…
🧭 https://blog.nootch.net/post/lto-drive-in-2018/Linear%20Tape-Open
🔗 https://blog.nootch.net/tags/networking/index.xml
🧭 https://blog.nootch.net/post/recently-2019-feb-24/2013
🔗 https://blog.nootch.net/tags/security/index.xml
🧭 https://blog.nootch.net/page/3/
🧭 https://blog.nootch.net/post/page/3/
🔗 https://googleads.g.doubleclick.net/pagead/id
✔  https://blog.nootch.net/tags/networking/index.xml
🔗 https://static.doubleclick.net/instream/ad_status.js
✔  https://blog.nootch.net/tags/security/index.xml
🔗 https://blog.nootch.net/tags/firefox/index.xml
🛑  https://googleads.g.doubleclick.net/pagead/id
file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:239
			body = body.toString().replaceAll(origin, '')
			            ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at onFile (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:239:16)
    at fetchURL (file:///home/sardaukar/.asdf/installs/nodejs/21.6.2/lib/node_modules/mpa-archive/src/archive.js:319:2)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.6.2
```

**Comment by titoBouzout** [comment]
Thanks for bringing attention to this issue! The problems have been fixed.  

I have added a domain blacklist to avoid saving/fetching pages from domains like `googleads.g.doubleclick.net`, which gets rid of the first error.  

The other errors such  `Error: net::ERR_ABORTED` seem to be caused by file downloads, downloads are canceled and not saved. When an error triggered by crawling(opening a tab) happens, it will retry but via `fetch` which will save the desired file in the zip file. I couldn't figure out how to stream the download to the zip, but a fetch request works. The error will still show up, but the file is successfully downloaded. 
```
🛑  https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus.key
Error: net::ERR_ABORTED at https://blog.nootch.net/img/post/amiga-bbs-online-2019/Zeus.key
```

Please note that I do not want to completely silent this error because we may discover other edge cases. The site seems to be achievable, so I consider this issue done.
